//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VODMovieWebSite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VODMovieWebSite.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li class=&apos;actor&apos;&gt;&lt;div class=&apos;actor-pic&apos;&gt;&lt;a href=&apos;#ACTOR_LINK#&apos;&gt;&lt;img class=&apos;shadow&apos; src=&apos;actors/#ACTOR_PHOTO#&apos; align=&apos;middle&apos;/&gt;&lt;/a&gt;&lt;/div&gt;&lt;div class=&apos;actor-text&apos;&gt;&lt;a href=&apos;#ACTOR_LINK#&apos;&gt;#ACTOR_NAME#&lt;br/&gt;(#ACTOR_CHARACTER#)&lt;/a&gt;&lt;/div&gt;&lt;/li&gt;.
        /// </summary>
        internal static string ActorTemplate {
            get {
                return ResourceManager.GetString("ActorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href = &apos;genres.htm?g={0}&apos; class=&apos;button button-gray&apos;&gt;{0}&lt;/a&gt;.
        /// </summary>
        internal static string GenreTemplate {
            get {
                return ResourceManager.GetString("GenreTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li class=&apos;thumbnail&apos;&gt;&lt;div class=&apos;thumbnail-pic&apos;&gt;&lt;a href=&apos;movie.htm?m={0}&apos;&gt;&lt;img border=&apos;0&apos; src=&apos;covers/{1}&apos; align=&apos;middle&apos;  loading=&quot;lazy&quot;&gt;&lt;/a&gt;&lt;/div&gt;&lt;div class=&apos;thumbnail-text&apos;&gt;&lt;a href=&apos;movie.htm?m={0}&apos;&gt;{2}&lt;/a&gt;&lt;/div&gt;&lt;/li&gt;.
        /// </summary>
        internal static string MovieTemplate {
            get {
                return ResourceManager.GetString("MovieTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;http://{0}&apos;&gt;&lt;img src=&apos;gif/imdb.gif&apos; alt=&apos;link to {1}&apos;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string TrailerTemplate {
            get {
                return ResourceManager.GetString("TrailerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;nav class=&apos;subnav&apos;&gt;&lt;a href=&apos;&apos;&gt;#YEAR#&lt;/a&gt;&lt;/nav&gt;&lt;article id =&apos;#YEAR#&apos;&gt;&lt;ul&gt;#YEAR_SECTION#&lt;/ul&gt;&lt;br/&gt;&lt;h2&gt;&lt;a href=&apos;#top&apos;&gt;Home&lt;/a&gt;&lt;/h2&gt;&lt;/article&gt;.
        /// </summary>
        internal static string YearSectionTemplate {
            get {
                return ResourceManager.GetString("YearSectionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;years.htm#{0}&apos; class=&apos;button button-gray&apos;&gt;{0}&lt;/a&gt;.
        /// </summary>
        internal static string YearTemplate {
            get {
                return ResourceManager.GetString("YearTemplate", resourceCulture);
            }
        }
    }
}
